name: Test repository when push

on:
  push:
  workflow_dispatch:

jobs:
  containers-test:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: 'Run testcontainers tests'
        run: mvn test -P testcontainersTest --file pom.xml
      - if: failure()
        name: 'Create failed issue'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: Testcontainers
          RUN-ID: ${{ github.run_id }}
          JOB-ID: ${{ github.job }}
          REF: ${{ github.ref }}
          REF-NAME: ${{ github.ref_name }}

  embedded-test:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: 'Run embedded(H2) tests'
        run: mvn verify --file pom.xml
      - if: failure()
        name: 'Create failed issue'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: Embedded
          RUN-ID: ${{ github.run_id }}
          JOB-ID: ${{ github.job }}
          REF: ${{ github.ref }}
          REF-NAME: ${{ github.ref_name }}
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true