name: Maven Library Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 for deploy to Sonatype
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)

      - name: Prepare Maven environment with Java 17 for deployment to Sonatype
        run: export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"

      - name: Publish to Apache Maven Central
        run: mvn deploy -P sonatypeDeploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "[skip ci] chore: update pom version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:main

  notify-on-failure:
    needs: publish
    if: failure()
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - if: failure()
        name: 'Create failed issue'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: Deploy
          RUN-ID: ${{ github.run_id }}
          JOB-ID: ${{ github.job }}
          REF: ${{ github.ref }}
          REF-NAME: ${{ github.ref_name }}